class News:
    mode = ""
    mid = ""
    sid = ""
    oid = ""
    aid = ""
    mTitle = ""
    mDate = ""
    mLink = ""
    mOriginalLink = ""
    mDescription = ""
    mContents = ""
    oh = ""
